version: '3'
services:
  spring:
    build: ./backend
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'todolist'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"
    volumes:
      - mysqldb-data:/var/lib/mysql

volumes:
  mysqldb-data:
